# Generated by Django 5.2.5 on 2025-08-21 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.CharField(max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=1)),
                ('lastName', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_number', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('current', 'Current'), ('done', 'Done'), ('skip', 'Skip'), ('cancel', 'Cancel'), ('standby', 'Standby')], default='pending', max_length=50)),
                ('is_priority', models.CharField(choices=[('yes', 'Yes')], default='no', max_length=50)),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personel.courses')),
                ('requestType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personel.requesttype')),
            ],
        ),
    ]
