# Generated by Django 5.2.5 on 2025-08-21 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentappointments',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personel.usertype'),
        ),
        migrations.AlterField(
            model_name='studentappointments',
            name='is_priority',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
    ]
