# Generated by Django 5.2.5 on 2025-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0002_studentappointments_usertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentappointments',
            name='skip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentappointments',
            name='skip_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
