# Generated by Django 5.2.5 on 2025-08-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0003_studentappointments_skip_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentappointments',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
