# Generated by Django 5.2.5 on 2025-08-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0004_alter_studentappointments_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentappointments',
            name='userType',
        ),
        migrations.AlterField(
            model_name='studentappointments',
            name='middleName',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
