# Generated by Django 5.2.5 on 2025-08-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0005_remove_studentappointments_usertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Offices',
        ),
    ]
