# Generated by Django 5.2.5 on 2025-08-26 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0006_personel_delete_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
