# Generated by Django 5.2.5 on 2025-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0007_personel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentappointments',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('guest', 'Guest')], default='student', max_length=50),
        ),
    ]
