# Generated by Django 5.2.5 on 2025-08-31 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0008_studentappointments_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=50)),
                ('student_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.studentappointments')),
            ],
        ),
    ]
