# Generated by Django 5.2.5 on 2025-09-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0009_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personel',
        ),
    ]
