# Generated by Django 5.2.5 on 2025-09-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0011_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
