# Generated by Django 5.2.5 on 2025-09-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0012_courses_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAppointments',
            new_name='Appointments',
        ),
    ]
