# Generated by Django 5.2.5 on 2025-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0013_rename_studentappointments_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AddField(
            model_name='appointments',
            name='custom_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='custom_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
