# Generated by Django 5.2.5 on 2025-09-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0014_delete_usertype_appointments_custom_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttype',
            name='custom_request',
        ),
    ]
