# Generated by Django 5.2.5 on 2025-09-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0015_remove_requesttype_custom_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='idNumber',
        ),
    ]
