# Generated by Django 5.2.5 on 2025-09-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0016_remove_appointments_idnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
