# Generated by Django 5.2.5 on 2025-09-10 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0017_delete_survey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='username',
        ),
        migrations.AddField(
            model_name='appointments',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_served', to='personel.personel'),
        ),
        migrations.AddField(
            model_name='personel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
