# Generated by Django 5.2.5 on 2025-09-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0018_remove_personel_password_remove_personel_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
