# Generated by Django 5.2.5 on 2025-09-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0019_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personel.appointments'),
        ),
        migrations.AddField(
            model_name='pin',
            name='used',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
