# Generated by Django 5.2.5 on 2025-09-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0020_pin_appointment_pin_used_alter_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('appointments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personel.appointments')),
            ],
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
