# Generated by Django 5.2.5 on 2025-09-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0021_code_delete_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='status',
            field=models.CharField(choices=[('unused', 'Unused'), ('used', 'Used')], default='unused', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='appointments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personel.appointments'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
