# Generated by Django 5.2.5 on 2025-12-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0022_code_created_at_code_status_alter_code_appointments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=True)),
            ],
        ),
    ]
