# Generated by Django 6.0 on 2025-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0023_queuecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='status',
            field=models.CharField(choices=[('unused', 'Unused'), ('pernding', 'Pernding'), ('used', 'Used')], default='pending', max_length=10, null=True),
        ),
    ]
