# Generated by Django 5.2.5 on 2025-09-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personel', '0021_code_delete_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCchoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceQualityDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CCquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('choices', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='survey.ccchoices')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government', models.CharField(max_length=50, null=True)),
                ('visit_date', models.DateField(null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('office_person', models.CharField(max_length=100, null=True)),
                ('service_availed', models.TextField(null=True)),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ccchoices', models.ManyToManyField(blank=True, to='survey.ccchoices')),
                ('ccquestions', models.ManyToManyField(blank=True, to='survey.ccquestion')),
                ('client_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.clienttype')),
                ('code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='personel.code')),
                ('sqd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.servicequalitydimension')),
            ],
        ),
    ]
