# Generated by Django 5.2.5 on 2025-09-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_goverment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goverment',
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='government',
            field=models.CharField(default='goverment', max_length=50, null=True),
        ),
    ]
