# Generated by Django 5.2.5 on 2025-09-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_delete_goverment_alter_satisfactionsurvey_government'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccquestion',
            name='choices',
        ),
        migrations.AddField(
            model_name='ccchoices',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.ccquestion'),
        ),
    ]
