# Generated by Django 5.2.5 on 2025-09-23 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_ccquestion_choices_ccchoices_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccchoices',
            name='question',
        ),
        migrations.AddField(
            model_name='ccquestion',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.ccchoices'),
        ),
    ]
