# Generated by Django 5.2.5 on 2025-09-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_ccchoices_question_ccquestion_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccquestion',
            name='choices',
        ),
        migrations.AddField(
            model_name='ccchoices',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.ccquestion'),
        ),
    ]
