# Generated by Django 5.2.5 on 2025-09-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_ccquestion_choices_ccchoices_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.ccquestion'),
        ),
    ]
