# Generated by Django 5.2.5 on 2025-09-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_ccchoices_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satisfactionsurvey',
            name='ccchoices',
        ),
        migrations.RemoveField(
            model_name='satisfactionsurvey',
            name='ccquestions',
        ),
        migrations.RemoveField(
            model_name='satisfactionsurvey',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='satisfactionsurvey',
            name='sqd',
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='government',
            field=models.CharField(default='government', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CCResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='survey.ccchoices')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.ccquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_responses', to='survey.satisfactionsurvey')),
            ],
        ),
        migrations.CreateModel(
            name='SQDResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('sqd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.servicequalitydimension')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqd_responses', to='survey.satisfactionsurvey')),
            ],
        ),
    ]
