# Generated by Django 5.2.5 on 2025-10-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_satisfactionsurvey_ccchoices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SQDYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_links', to='survey.servicequalitydimension')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqd_links', to='survey.surveyyear')),
            ],
            options={
                'unique_together': {('year', 'sqd')},
            },
        ),
        migrations.CreateModel(
            name='QuestionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_links', to='survey.ccquestion')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='survey.surveyyear')),
            ],
            options={
                'unique_together': {('year', 'question')},
            },
        ),
    ]
