# Generated by Django 5.2.5 on 2025-10-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_surveyyear_sqdyear_questionyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sqdresponse',
            name='sqd',
        ),
        migrations.AddField(
            model_name='ccresponse',
            name='question_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.questionyear'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='survey_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='survey.surveyyear'),
        ),
        migrations.AddField(
            model_name='sqdresponse',
            name='sqd_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.sqdyear'),
        ),
        migrations.AlterField(
            model_name='ccchoices',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ccchoices',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.ccquestion'),
        ),
        migrations.AlterField(
            model_name='ccquestion',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clienttype',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='questionyear',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_links', to='survey.ccquestion'),
        ),
        migrations.AlterField(
            model_name='questionyear',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='survey.surveyyear'),
        ),
        migrations.AlterField(
            model_name='servicequalitydimension',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sqdresponse',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='sqdresponse',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sqd_responses', to='survey.satisfactionsurvey'),
        ),
        migrations.AlterField(
            model_name='sqdyear',
            name='sqd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_links', to='survey.servicequalitydimension'),
        ),
        migrations.AlterField(
            model_name='sqdyear',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sqd_links', to='survey.surveyyear'),
        ),
        migrations.AlterField(
            model_name='surveyyear',
            name='year',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
