# Generated by Django 5.2.5 on 2025-10-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_remove_ccresponse_question_remove_sqdresponse_sqd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccresponse',
            name='choices',
        ),
        migrations.AddField(
            model_name='ccresponse',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.ccchoices'),
        ),
        migrations.AlterField(
            model_name='ccresponse',
            name='question_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.questionyear'),
        ),
        migrations.AlterField(
            model_name='ccresponse',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_responses', to='survey.satisfactionsurvey'),
        ),
    ]
