# Generated by Django 5.2.5 on 2025-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_ccresponse_choices_ccresponse_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccchoices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ccquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ccresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicequalitydimension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sqdresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
