# Generated by Django 5.2.5 on 2025-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_remove_ccquestion_updated_at_alter_ccquestion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccquestion',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
