# Generated by Django 5.2.5 on 2025-12-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_ccquestion_updated_at_alter_ccquestion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqdresponse',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
