# Generated by Django 5.2.5 on 2025-08-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientType', models.CharField(choices=[('citizen', 'Citizen'), ('business', 'Business'), ('government', 'Government'), ('ngo', 'NGO')], max_length=20)),
                ('visitDate', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('officePerson', models.CharField(max_length=100)),
                ('serviceAvailed', models.TextField()),
            ],
        ),
    ]
