# Generated by Django 5.2.5 on 2025-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='government',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('agency', 'Other Agency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='clientType',
            field=models.CharField(choices=[('citizen', 'Student Applicant'), ('business', 'Citizen (Student/Parents/Alumni)'), ('government', 'Business')], max_length=50),
        ),
    ]
