# Generated by Django 5.2.5 on 2025-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_satisfactionsurvey_government_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientType', models.CharField(max_length=50)),
                ('government', models.CharField(blank=True, max_length=50, null=True)),
                ('visitDate', models.DateField()),
                ('sex', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('officePerson', models.CharField(max_length=100)),
                ('serviceAvailed', models.TextField()),
                ('cc1', models.CharField(blank=True, max_length=10, null=True)),
                ('cc2', models.CharField(blank=True, max_length=10, null=True)),
                ('cc3', models.CharField(blank=True, max_length=10, null=True)),
                ('sod_ratings', models.JSONField(default=dict)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SatisfactionSurvey',
        ),
    ]
