# Generated by Django 5.2.5 on 2025-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_surveyresponse_delete_satisfactionsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientType', models.CharField(choices=[('citizen', 'Student Applicant'), ('business', 'Citizen(Student/Parents/Alumni)'), ('government', 'Business')], max_length=50)),
                ('government', models.CharField(choices=[('employee', 'Employee'), ('other-agency', 'Other Agency')], max_length=50)),
                ('visitDate', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('officePerson', models.CharField(max_length=100)),
                ('serviceAvailed', models.TextField()),
                ('cc1', models.CharField(blank=True, max_length=50, null=True)),
                ('cc2', models.CharField(blank=True, max_length=50, null=True)),
                ('cc3', models.CharField(blank=True, max_length=50, null=True)),
                ('ratings', models.JSONField(default=dict)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
