# Generated by Django 5.2.5 on 2025-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_satisfactionsurvey_delete_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientType', models.CharField(choices=[('student_applicant', 'Student Applicant'), ('citizen', 'Citizen (Student/Parents/Alumni)'), ('business', 'Business')], max_length=50)),
                ('government', models.CharField(choices=[('employee', 'Employee'), ('other_agency', 'Other Agency')], max_length=50)),
                ('visitDate', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('officePerson', models.CharField(max_length=100)),
                ('serviceAvailed', models.TextField()),
                ('cc1', models.IntegerField(blank=True, null=True)),
                ('cc2', models.IntegerField(blank=True, null=True)),
                ('cc3', models.IntegerField(blank=True, null=True)),
                ('sod0', models.IntegerField(blank=True, null=True)),
                ('sod1', models.IntegerField(blank=True, null=True)),
                ('sod2', models.IntegerField(blank=True, null=True)),
                ('sod3', models.IntegerField(blank=True, null=True)),
                ('sod4', models.IntegerField(blank=True, null=True)),
                ('sod5', models.IntegerField(blank=True, null=True)),
                ('sod6', models.IntegerField(blank=True, null=True)),
                ('sod7', models.IntegerField(blank=True, null=True)),
                ('sod8', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SatisfactionSurvey',
        ),
    ]
