# Generated by Django 5.2.5 on 2025-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_surveyresponse_cc1_alter_surveyresponse_cc2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientType', models.CharField(max_length=100)),
                ('government', models.CharField(max_length=100)),
                ('visitDate', models.DateField()),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('region', models.CharField(max_length=200)),
                ('officePerson', models.CharField(max_length=200)),
                ('serviceAvailed', models.TextField()),
                ('cc1', models.CharField(max_length=200)),
                ('cc2', models.CharField(max_length=10)),
                ('cc3', models.CharField(max_length=10)),
                ('sod0', models.IntegerField()),
                ('sod1', models.IntegerField()),
                ('sod2', models.IntegerField()),
                ('sod3', models.IntegerField()),
                ('sod4', models.IntegerField()),
                ('sod5', models.IntegerField()),
                ('sod6', models.IntegerField()),
                ('sod7', models.IntegerField()),
                ('sod8', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
