# Generated by Django 5.2.5 on 2025-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_satisfactionsurvey_delete_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='cc2',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='cc3',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='clientType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='government',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='officePerson',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
