# Generated by Django 5.2.5 on 2025-08-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_satisfactionsurvey_cc2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
