# Generated by Django 5.2.5 on 2025-09-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
