# Generated by Django 5.2.5 on 2025-09-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_pin_created_at_alter_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('unused', 'Unused'), ('used', 'Used')], default='unused', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='playground.pin', unique=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
