# Generated by Django 5.2.5 on 2025-09-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0017_delete_survey'),
        ('playground', '0011_pin_status_satisfactionsurvey_pin_alter_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='appointments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personel.appointments', unique=True),
        ),
    ]
