# Generated by Django 5.2.5 on 2025-09-10 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0018_remove_personel_password_remove_personel_username_and_more'),
        ('playground', '0012_pin_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='appointments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personel.appointments'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='pin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='playground.pin'),
        ),
    ]
